# Generated by Django 5.1.3 on 2025-02-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='recipient',
        ),
        migrations.AddField(
            model_name='visitor',
            name='recipient_department',
            field=models.CharField(max_length=100, null=True, verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='recipient_full_name',
            field=models.CharField(max_length=100, null=True, verbose_name='к кому ФИО'),
        ),
    ]
