# Generated by Django 5.1.3 on 2025-02-03 06:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_visitor_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='visit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
