# Generated by Django 5.1.3 on 2025-02-03 06:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_visitor_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='visit_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
