# Generated by Django 5.1.3 on 2025-02-04 04:17

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_visitor_visit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='visit_time',
            field=models.TimeField(default=myapp.models.get_local_time, verbose_name='Время визита'),
        ),
    ]
