# Generated by Django 5.1.3 on 2025-03-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_visitor_visit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='recipient_department',
            field=models.CharField(choices=[('отдел1', 'Отдел 1'), ('отдел2', 'Отдел 2'), ('отдел3', 'Отдел 3')], max_length=100, null=True, verbose_name='Отдел'),
        ),
    ]
